"""
Rebuttal-facing LaTeX table + plain-text summary for the time-resolved
bottleneck/residual-correlation analysis.

Reads the JSON written by curvature_bottleneck_residual_corr_timeresolved.py
for one or more datasets and emits:
  * the pre-specified window table (beta_b, Spearman rho, Holm-corrected p)
  * the primary and control contrasts
Reports whatever is in the JSON, including null and negative results -- there is
no filtering of windows by outcome anywhere in this file.

Usage:
    python src/curvature_timeresolved_table.py \\
        --json metrics_stat/xLSTM/brussels_xlstm_bottleneck_residual_corr_timeresolved.json \\
        --json metrics_stat/xLSTM/pems03_xlstm_bottleneck_residual_corr_timeresolved.json \\
        --tex-out NeurIPS/timeresolved_bottleneck_table.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List

WINDOW_ORDER = ["night", "am_shoulder", "am_peak", "midday", "pm_peak", "pm_shoulder"]
PRETTY = {
    "night": "Night 22--05 (free flow)",
    "am_shoulder": "Onset 05--07",
    "am_peak": "AM peak 07--10 (congested)",
    "midday": "Midday 10--16",
    "pm_peak": "PM peak 16--19 (congested)",
    "pm_shoulder": "Decay 19--22",
}


def stars(p: float) -> str:
    return "$^{***}$" if p < 0.001 else "$^{**}$" if p < 0.01 else "$^{*}$" if p < 0.05 else ""


def window_rows(results: Dict, daytype: str) -> List[str]:
    windows = results["analysis"]["windows"]
    rows = []
    for label in WINDOW_ORDER:
        w = windows.get(f"{label}__{daytype}", {})
        if "beta_bottleneck_adjusted" not in w:
            rows.append(f"{PRETTY[label]} & \\multicolumn{{5}}{{c}}{{--- skipped: {w.get('skipped_reason', 'n/a')} ---}} \\\\")
            continue
        nb = w["beta_bottleneck_adjusted_null"]
        rows.append(
            f"{PRETTY[label]} & {w['n_origins']} & {w['effective_n_origins_ar1']:.0f} & "
            f"${w['beta_bottleneck_adjusted']:+.4f}$ & ${nb['z_score']:+.2f}$ & "
            f"{nb['p_value_holm']:.3f}{stars(nb['p_value_holm'])} & "
            f"${w['spearman_rho_adjusted']:+.3f}$ \\\\"
        )
    return rows


def dataset_block(results: Dict) -> List[str]:
    name = results["dataset"]
    lines = [
        f"\\multicolumn{{7}}{{l}}{{\\emph{{{name} / {results['model']}, "
        f"{results['span']['span_start']} to {results['span']['span_end']}, "
        f"{results['span']['n_origins_used']} rolling origins, {results['n_edges']} edges}}}} \\\\",
        "\\midrule",
        "\\multicolumn{7}{l}{\\textbf{Weekdays}} \\\\",
    ]
    lines += window_rows(results, "weekday")
    lines += ["\\addlinespace", "\\multicolumn{7}{l}{\\textbf{Weekends (control)}} \\\\"]
    lines += window_rows(results, "weekend")
    return lines


def contrast_lines(results: Dict) -> List[str]:
    out = []
    for key in ("weekday", "weekend"):
        c = results["analysis"]["contrasts"].get(key, {})
        if "delta" not in c:
            out.append(f"  {results['dataset']} {key}: skipped ({c.get('skipped_reason')})")
            continue
        out.append(
            f"  {results['dataset']:12s} {key:8s} Delta={c['delta']:+.5f}  z={c['z_score']:+6.2f}  "
            f"p_one_sided={c['p_value_one_sided_greater']:.4f}  "
            f"[beta_peak={c['beta_peak']:+.5f}, beta_night={c['beta_reference']:+.5f}]"
        )
    dd = results["analysis"]["contrasts"].get("weekday_minus_weekend", {})
    if "delta_of_deltas" in dd:
        out.append(f"  {results['dataset']:12s} weekday-minus-weekend delta_of_deltas={dd['delta_of_deltas']:+.5f}")
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="append", required=True)
    parser.add_argument("--tex-out", required=True)
    args = parser.parse_args()

    all_results = [json.loads(Path(p).read_text()) for p in args.json]

    body: List[str] = []
    for i, results in enumerate(all_results):
        if i:
            body.append("\\addlinespace[4pt]")
        body += dataset_block(results)

    tex = "\n".join(
        [
            "% Auto-generated by src/curvature_timeresolved_table.py -- do not edit by hand.",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{Residual correlation vs.\\ curvature bottleneck score, resolved by traffic regime. "
            "$\\beta_b$ is the coefficient on the standardised bottleneck score in "
            "$|\\rho_{ij}| \\sim 1 + z(b_{ij}) + z(\\mathrm{dist}_{ij}) + z(\\deg_{ij})$; "
            "$z$ and $p$ are from a node-permutation null (10{,}000 permutations) that holds the graph, "
            "$b$, distance and degree fixed. $p$ is Holm-corrected across the 12 window tests. "
            "$\\rho_S^{\\mathrm{adj}}$ is the Spearman rank correlation between $b_{ij}$ and $|\\rho_{ij}|$ "
            "after removing distance and degree. Windows, hypothesis and the primary contrast were fixed "
            "before any window-resolved quantity was computed. Residuals are in-sample (see text).}",
            "\\label{tab:timeresolved-bottleneck}",
            "\\begin{tabular}{lrrrrrr}",
            "\\toprule",
            "Window & $T$ & $T_{\\mathrm{eff}}$ & $\\beta_b$ & $z$ & $p_{\\mathrm{Holm}}$ & $\\rho_S^{\\mathrm{adj}}$ \\\\",
            "\\midrule",
        ]
        + body
        + ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    )

    tex_out = Path(args.tex_out)
    tex_out.parent.mkdir(parents=True, exist_ok=True)
    tex_out.write_text(tex)
    print(f"Wrote {tex_out}\n")

    print("=== PRIMARY (weekday) and CONTROL (weekend) contrasts ===")
    print("H1 requires: weekday Delta > 0 and larger than weekend Delta.\n")
    for results in all_results:
        for line in contrast_lines(results):
            print(line)


if __name__ == "__main__":
    main()
